#!/usr/bin/env node
/**
 * @fileoverview This script generates a `src/version.ts` file that exports
 * build-time information, such as the git commit SHA and the build timestamp.
 * This information is then used by the application, for example in the health
 * check endpoint.
 */
const { execSync } = require('node:child_process')
const { writeFileSync, mkdirSync } = require('node:fs')
const { resolve, dirname } = require('node:path')

/**
 * Executes a shell command and returns its stdout.
 * @param {string} cmd - The command to execute.
 * @returns {string} The trimmed stdout of the command, or an empty string if it fails.
 */
function sh(cmd) { try { return execSync(cmd, { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim() } catch { return '' } }

// Main logic
const commit = process.env.GITHUB_SHA || sh('git rev-parse --verify HEAD') || 'unknown'
const short = commit ? commit.slice(0, 7) : 'unknown'
const buildTime = new Date().toISOString()

const out = `// AUTO-GENERATED by scripts/gen-version.cjs

/**
 * The full git commit SHA of the build.
 * @type {string}
 */
export const COMMIT_SHA = '${commit}';

/**
 * The short git commit SHA of the build.
 * @type {string}
 */
export const COMMIT_SHORT = '${short}';

/**
 * The ISO string of the build time.
 * @type {string}
 */
export const BUILD_TIME = '${buildTime}';
`;

const target = resolve(__dirname, '..', 'src', 'version.ts')
mkdirSync(dirname(target), { recursive: true })
writeFileSync(target, out, 'utf8')
console.log(`[gen-version] commit=${short} time=${buildTime}`)