#!/usr/bin/env node const { execSync } = require('node:child_process') const { writeFileSync, mkdirSync } = require('node:fs') const { resolve, dirname } = require('node:path')

function sh(cmd) { try { return execSync(cmd, { stdio: ['ignore','pipe','ignore'] }).toString().trim() } catch { return '' } }

const commit = process.env.GITHUB_SHA || sh('git rev-parse --verify HEAD') || 'unknown' const short = commit ? commit.slice(0, 7) : 'unknown' const buildTime = new Date().toISOString()

const out = // AUTO-GENERATED by scripts/gen-version.cjs export const COMMIT_SHA = '${commit}'; export const COMMIT_SHORT = '${short}'; export const BUILD_TIME = '${buildTime}';

const target = resolve(__dirname, '..', 'src', 'version.ts') mkdirSync(dirname(target), { recursive: true }) writeFileSync(target, out, 'utf8') console.log([gen-version] commit=${short} time=${buildTime})
