// AUTO-GENERATED by scripts/gen-version.cjs
export const COMMIT_SHA = '0bddab2106c5ab8bb402c2906a0743682ebf5fbe';
export const COMMIT_SHORT = '0bddab2';
export const BUILD_TIME = '2025-08-23T09:21:59.211Z';
