// AUTO-GENERATED by scripts/gen-version.cjs
export const COMMIT_SHA = '78b08930ebfb431e77d51e7629fc1ded7ae55fa2';
export const COMMIT_SHORT = '78b0893';
export const BUILD_TIME = '2025-08-19T03:59:06.881Z';
