// AUTO-GENERATED by scripts/gen-version.cjs
export const COMMIT_SHA = 'cc54b03e04b6abfe97555786d793510782c6f08f';
export const COMMIT_SHORT = 'cc54b03';
export const BUILD_TIME = '2025-08-23T09:38:34.270Z';
